services:
  db:
    image: postgres:17-alpine
    container_name: precificacao-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    container_name: precificacao-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_PASSWORD}
      #APP_CORS_ALLOWED_ORIGIN: http://localhost:3000
      APP_CORS_ALLOWED_ORIGIN: http://192.168.0.10:3000
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        #VITE_API_BASE_URL: http://localhost:8080
        VITE_API_BASE_URL: http://192.168.0.10:8080
    container_name: precificacao-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data: